service: service1

useDotenv: true
variablesResolutionMode: 20210219

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  versionFunctions: false
  apiGateway:
    restApiId:
      'Fn::ImportValue': MyApiGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': MyApiGateway-rootResourceId
  
functions:
  myhandler2:
    handler: ./service1/handler1.handle
    events:
      - http:
          method: post
          path: service1/handler
          request:
            schemas:
              application/json: ${file(./service1/schema1.json)}

